app = "bonk-api"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "flyio/bonk-api:latest"

[deploy]
  strategy = "rolling"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
