name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - name: Check Go fmt
        run: nix develop --command sh -c 'gofmt -l . && test -z "$(gofmt -l .)"'

  build-x86_64-linux:
    name: Build x86_64 Linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build server
        run: nix build --print-build-logs .#packages.x86_64-linux.bonk
      - name: Build docker image
        run: |
          nix build .#packages.x86_64-linux.dockerImage
